version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - ENV=development
    depends_on:
      - api

  api:
    build:
      context: ./src/api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - ENV=development
    volumes:
      - ./src/api:/app/src/api

networks:
  default:
    driver: bridge

volumes:
  data: